---
title: "POMA: Statistical analysis tool for targeted metabolomic data"
subtitle: "Automatic Statistical Analysis: Metabolomic analysis for more than 2 groups using default 'Pre-processing' by POMA"
date: '`r format(Sys.Date(), "%B, %Y")`'
output:
  prettydoc::html_pretty:
    toc: true
    toc_depth: 3
    theme: cayman
    highlight: github
params:
  n: NA
---

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
# This file is part of POMA.

# POMA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# POMA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with POMA. If not, see <https://www.gnu.org/licenses/>.

options(knitr.table.format = "html") 

data <- params$n
colnames(data)[1:2] <- c("ID", "Group")
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
samples_group <- data[,1:2]
data <- data[,c(-1,-2)]
#remove zeros
data <- data[, which(colSums(data) != 0)]
#remove NAs
data <- data[,apply(data,2,function(x) !all(is.na(x)))] 
#
data <- cbind(samples_group, data)
#supress >20% NA by group
count_NA <- aggregate(. ~ Group, data = data[,2:length(data)], function(x) {100*(sum(is.na(x))/(sum(is.na(x))+sum(!is.na(x))))}, 
                                            na.action = NULL)
supress <- c(count_NA[1,] > 20 | count_NA[2,] > 20)
data <- data[,2:length(data)][,!supress]
#impute NA by knn
depurdata<-data
depurdata<-t(depurdata)
datai<-impute::impute.knn(as.matrix(depurdata))
depurdata<-t(datai$data)
#normalisation
data_norm <- round(apply(depurdata,2,function(x) (log10(x+1))),3)
data_norm <-cbind(samples_group,data_norm)
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
#normality
normality <- data.frame(pval=apply(data_norm[,3:ncol(data_norm)],2,function(x) {shapiro.test(x)$p.value}))
normality$pval <- p.adjust(normality$pval, method = "fdr")
normality$names <- rownames(normality)
names.normality <- normality[normality$pval >= 0.05,2]
names.non.normality <- normality[normality$pval < 0.05,2]
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
## NORMAL
data_no <- data_norm[,colnames(data_norm) %in% names.normality]
data_no <-cbind(samples_group,data_no)

if(ncol(data_no) == 3){
  colnames(data_no)[3]<-colnames(data_norm)[colnames(data_norm) %in% names.normality]
}

## NON NORMAL
data_non_no <- data_norm[,colnames(data_norm) %in% names.non.normality]
data_non_no <-cbind(samples_group,data_non_no)

if(ncol(data_non_no) == 3){
  colnames(data_non_no)[3]<-colnames(data_norm)[colnames(data_norm) %in% names.non.normality]
}

```

# Parametric tests

## ANOVA

### Metabolites with NORMAL distribution

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}

Group <- as.factor(data_no$Group)

if(ncol(data_no)>3){
  
stat2 <- function(x){anova(aov(x ~ Group, data=data_no))$"Pr(>F)"[1]}
p2 <- as.data.frame(apply(FUN=stat2, MARGIN = 2, X = data_no[,c(3:ncol(data_no))]))
colnames(p2) <- c("P.Value")
p2$adj.P.Val <- p.adjust(p2$P.Value, method = "fdr")

p2 <- round(p2,5)
p2 <- p2[order(p2$adj.P.Val, decreasing = FALSE),]

p2 %>%
  mutate(Metabolite = row.names(.))%>%
       # adj.P.Val = cell_spec(adj.P.Val, "html", 
       #                       color = ifelse(adj.P.Val <= 0.05, "red", "black"))) %>%
  dplyr::select(Metabolite, P.Value, adj.P.Val) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)
}

if(ncol(data_no) == 3){
  
p2 <- data.frame(anova(aov(data_no[,3] ~ Group, data=data_no))$"Pr(>F)"[1])
colnames(p2) <- c("P.Value")

p2 <- round(p2,5)

p2 %>%
  mutate(Metabolite = row.names(.))%>%
       # P.Value = cell_spec(P.Value, "html", 
       #                       color = ifelse(P.Value <= 0.05, "red", "black"))) %>%
  dplyr::select(Metabolite, P.Value) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)
}

```

# Non Parametric tests 

## Kruskal Wallis Test

### Metabolites with NON NORMAL distribution

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}

Group <- as.factor(data_non_no$Group)

if(ncol(data_non_no)>3){

p2 <- as.data.frame(apply(data_non_no[,3:ncol(data_non_no)],2,function(x){kruskal.test(x ~ as.factor(Group))$p.value}))
colnames(p2) <- c("P.Value")
p2$adj.P.Val <- p.adjust(p2$P.Value, method = "fdr")

p2 <- round(p2,5)
p2 <- p2[order(p2$adj.P.Val, decreasing = FALSE),]

p2 %>%
  mutate(Metabolite = row.names(.))%>%
       # adj.P.Val = cell_spec(adj.P.Val, "html", 
       #                       color = ifelse(adj.P.Val <= 0.05, "red", "black"))) %>%
  dplyr::select(Metabolite, P.Value, adj.P.Val) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)
}

if(ncol(data_no) == 3){
  
p2 <- data.frame(kruskal.test(data_non_no[,3] ~ as.factor(Group))$p.value)
colnames(p2) <- c("P.Value")

p2 <- round(p2,5)

p2 %>%
  mutate(Metabolite = row.names(.))%>%
       # P.Value = cell_spec(P.Value, "html", 
       #                       color = ifelse(P.Value <= 0.05, "red", "black"))) %>%
  dplyr::select(Metabolite, P.Value) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)
}
```

