## ==================================================================================== ##
# HELPERS
## ==================================================================================== ##

library(shiny) 
library(DT)
library(shinydashboard)
library(reshape2)
library(ggplot2)
library(impute)
library(gplots)
#library(rjson)
library(scales)
library(ggbiplot) #devtools::install_github("vqv/ggbiplot")
library(plotly)
library(readxl)
library(glmnet)
library(ggvis)
library(shinyhelper)
library(glue)
library(dashboardthemes) #devtools::install_github("nik01010/dashboardthemes")
library(tidyr)
library(limma)
library(mixOmics)
library(ggthemes)
library(dplyr)
library(ggrepel)
library(ggfortify)
library(shinyBS)
library(markdown)
library(readr)
library(broom)
