## ==================================================================================== ##
# HELPERS
## ==================================================================================== ##

library(shiny) #devtools::install_github("rstudio/shiny"); devtools::install_github("rstudio/shinyapps")
library(DT)
library(shinydashboard)
library(reshape2)
library(ggplot2)
library(impute)
#library(shinyIncubator) #devtools::install_github("rstudio/shinyIncubator")
library(gplots)
#library(rjson)
#library(base64enc)
library(ggbiplot)
library(plotly)
library(readxl)
library(glmnet)
library(ggvis)
library(shinyhelper)
library(glue)
library(dashboardthemes)
library(tidyr)
library(limma)
library(mixOmics)
library(ggthemes)
library(dplyr)
library(ggrepel)
#library(edgeR)
#library(RColorBrewer)
library(ggfortify)
library(shinyBS)
#library(plotly)
#library(plot3D)
library(markdown)
#library(lazyeval)
#library(rgl)
#library(scales)
#library(heatmaply)
library(readr)
library(broom)
