---
title: "POMA: Statistical analysis tool for targeted metabolomic data"
subtitle: "Intelligent Statistical Analysis"
date: '`r format(Sys.Date(), "%B, %Y")`'
output: 
  pdf_document:
    toc: yes
params:
  n: NA
---

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
#data <- params$n
data <- read_csv("/Users/pol/Dropbox/Shiny_apps/POMA/ST000284/MET_CRC_ST000284.csv")
colnames(data)[1:2] <- c("ID", "Group")
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
samples_group <- data[,1:2]
data <- data[,c(-1,-2)]
#remove zeros
data <- data[, which(colSums(data) != 0)]
#remove NAs
data <- data[,apply(data,2,function(x) !all(is.na(x)))] 
#
data <- cbind(samples_group, data)
#supress >20% NA by group
count_NA <- aggregate(. ~ Group, data = data[,2:length(data)], function(x) {100*(sum(is.na(x))/(sum(is.na(x))+sum(!is.na(x))))}, 
                                            na.action = NULL)
supress <- c(count_NA[1,] > 20 | count_NA[2,] > 20)
data <- data[,2:length(data)][,!supress]
#impute NA by knn
depurdata<-data
depurdata<-t(depurdata)
datai<-impute::impute.knn(as.matrix(depurdata))
depurdata<-t(datai$data)
#normalisation
data_norm <- round(apply(depurdata,2,function(x) (log10(x+1)-mean(log10(x+1),na.rm=T))/sd(log10(x+1),na.rm=T)),3)
data_norm <-cbind(samples_group,data_norm)
```

```{r, echo = FALSE, warning = FALSE, comment = NA, message=FALSE}
#normality
normality <- data.frame(pval=apply(data[,3:ncol(data)],2,function(x) {shapiro.test(x)$p.value}))
normality$pval <- p.adjust(normality$pval, method = "fdr")
normality$names <- rownames(normality)
names.normality <- normality[normality$pval >= 0.05,2]
names.non.normality <- normality[normality$pval < 0.05,2]
#homodasticity
homo <- data.frame(pval=apply(data[,3:ncol(data)],2,function(x) {bartlett.test(x, data$Group)$p.value}))
homo$pval <- p.adjust(homo$pval, method = "fdr")
homo$names <- rownames(homo)
names.homo <- homo[homo$pval >= 0.05,2]
names.non.homo <- homo[homo$pval < 0.05,2]
```





